on: [push]

name: Run Synthetics tests using the test public IDs.
jobs:
  e2e_testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Datadog Synthetic tests
        uses: DataDog/synthetics-ci-github-action@v0.2.1
        with:
          api_key: ${{secrets.DD_API_KEY}}
          app_key: ${{secrets.DD_APP_KEY}}
          public_ids: '5e9-g7r-spw, grf-ytd-qr3, upt-x28-7ru'
